services:
  - type: web
    name: platega
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile.render
    buildArgs:
      - CACHE_BUST=1724423513
    envVars:
      - key: SERVER_PORT
        value: 8080
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_ACCESS_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_DISPUTE_CHAT_ID
        sync: false
      - key: RATE_LIMIT_RPS
        value: "100"
      - key: BASE_URL
        value: https://platega.onrender.com
